### ISSUE TITLE
Error in JA3Digest

### ISSUE THREAD

**Issue by kjelle** [D4-project/sensor-d4-tls-fingerprinting#13]
Hello.
There seem to be an error in how the JA3Digest is outputted for some PCAPs. There are two bugs:

- The EllipticCurves part might be ending with a dash (-), probably from some GREASE filtering.
- The EllipticCurves field is missing the GREASE filtering.

Example:

> 771,49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53-10,65281-0-23-35-13-5-18-16-30032-11-10-,64250-29-23-24,0

Im preparing a patch.

**Comment by gallypette** [comment]
Yep your are totally right - Elliptics are missing GREASE filtering.
I reckon it causes the trailing dash too.

> Im preparing a patch.

I am looking forward to it !

**Comment by gallypette** [comment]
This should be addressed by 01695baaeef0f98f2d26c3e2d0eaef5dbfe37be6 
Reopen if you experience failures.
