### ISSUE TITLE
 Parse JA3 string 

### ISSUE THREAD

**Issue by 89z** [D4-project/sensor-d4-tls-fingerprinting#20]
Is it possible to do this?

**Comment by gallypette** [comment]
Hi, 
What do you mean by parsing? Creating JA3 fingerprints as described [here](https://github.com/salesforce/ja3#how-it-works)?
if that's is what you mean then yes.

**Comment by 89z** [comment]
I mean making an HTTPS request, using JA3 string as input

**Comment by gallypette** [comment]
Nope sorry, it does not do that.
